<?php

$LOCAL_LANG = Array (
	'default' => Array (
		'tt_products' => 'Products',
		'tt_products.price' => 'Price:',
		'tt_products.price2' => 'Price2:',
		'tt_products.price2_qty' => 'Price2 from qty:',
        'tt_products.price_factor' => 'Price multiplier:',
		'tt_products.weight' => 'Weight [kg]:',		
		'tt_products.unit' => 'Unit of measure',	
		'tt_products.unit_factor' => 'Unit factor',			
		'tt_products.itemnumber' => 'Item code:',
		'tt_products.inStock' => 'In Stock (pcs):',
		'tt_products.inStock_low' => 'Low stock (pcs):',
		'tt_products.on_demand' => 'On demand (days):',
		'tt_products.datasheet' => 'Datasheet (pdf)',		
		'tt_products_language_overlay' => 'Products (alternative language)',
		'tt_products_language_overlay.prd_uid' => 'Product record',
		'tt_products_language_overlay.sys_language_uid' => 'Language',		
		'tt_products_language_overlay.datasheet' => 'Datasheet (pdf)',		
		'tt_products_cat' => 'Product category',
		'tt_products_cat.parent_cat' => 'Parent category',					
		'tt_products_cat_language_overlay' => 'Product category (alternative language)',
		'tt_products_cat_language_overlay.sys_language_uid' => 'Language',
		'tt_products_cat_language_overlay.cat_uid' => 'Product category record',
        'tt_products_post_rates' => 'Postal rates',
	    'tt_products_post_rates.weight_limit' => 'weight up to [kg]:',
	    'tt_products_post_rates.local_rate' => 'Local rate :',
	    'tt_products_post_rates.a1_rate' => 'A1 rate :',
	    'tt_products_post_rates.a2_rate' => 'A2 rate :',
	    'tt_products_post_rates.a3_rate' => 'A3 rate :',
	    'tt_products_post_rates.a4_rate' => 'A4 rate :',
	    'tt_products_post_rates.a5_rate' => 'A5 rate :',
	    'tt_products_post_rates.b_rate' => 'B rate :',
	    'tt_products_post_rates.c_rate' => 'C rate :',
	    'tt_products_post_rates.d_rate' => 'D rate :',
		"tt_content.list_type_pi1" => "Products",		
		'tt_content.pi_flexform.display_mode' => 'Display mode',
		'tt_content.pi_flexform.display_mode.1' => 'Products: list',
	    'tt_content.pi_flexform.display_mode.2' => 'Produkts: records',
		'tt_content.pi_flexform.display_mode.3' => 'Products: single',
		'tt_content.pi_flexform.display_mode.4' => 'Products: search',	
		'tt_content.pi_flexform.display_mode.5' => 'Basket: content',
		'tt_content.pi_flexform.display_mode.6' => 'Basket: payment',
		'tt_content.pi_flexform.display_mode.7' => 'Basket: finalize',		
		'tt_content.pi_flexform.display_mode.8' => 'Basket: info',
		'tt_content.pi_flexform.display_mode.9' => 'Orders: tracking',		
		'tt_content.pi_flexform.display_mode.10' => 'Currency: selector',	
		'tt_content.pi_flexform.display_mode.11' => 'Product counter',	
		'tt_content.pi_flexform.product_records' => 'Selected products',
		'tt_products.prd_config' => "Product configuration:",
	),
	'dk' => Array (
		'tt_products' => 'Produkter',
		'tt_products.price' => 'Pris:',
		'tt_products.price2' => 'Pris (2):',
		'tt_products.itemnumber' => 'Emne nummer:',
		'tt_products.inStock' => 'P� lager (stk):',
		'tt_products_cat' => 'Produkt kategori',
	),
	'de' => Array (
		'tt_products' => 'Produkte',
		'tt_products.price' => 'Preis:',
		'tt_products.price2' => 'Preis (2):',
		'tt_products.itemnumber' => 'Artikel Nr.:',
		'tt_products.inStock' => 'Am Lager (St.):',
		'tt_products_cat' => 'Produkt Kategorie',
	),
	'no' => Array (
		'tt_products' => 'Produkter',
		'tt_products.price' => 'Pris:',
		'tt_products.price2' => 'Pris (2):',
		'tt_products.itemnumber' => 'Emne nummer:',
		'tt_products.inStock' => 'P� lager (stk.):',
		'tt_products_cat' => 'Produkt kategori',
	),
	'it' => Array (
		'tt_products' => 'Prodotti',
		'tt_products.price' => 'Prezzo:',
		'tt_products.price2' => 'Prezzo (2):',
		'tt_products.itemnumber' => 'Codice oggetto:',
		'tt_products.inStock' => 'In giacenza (p.zi):',
		'tt_products_cat' => 'Categoria prodotto',
	),
	'fr' => Array (
		'tt_products' => 'Produits',
		'tt_products.price' => 'Prix:',
		'tt_products.price2' => 'Prix (2):',
		'tt_products.itemnumber' => 'No article:',
		'tt_products.inStock' => 'En stocks (pcs):',
		'tt_products_cat' => 'Cat�gorie de produit',
	),
	'es' => Array (
		'tt_products' => 'Productos',
		'tt_products.price' => 'Precio:',
		'tt_products.price2' => 'Precio (2):',
		'tt_products.itemnumber' => 'N� de parte:',
		'tt_products.inStock' => 'En existencia (pz.):',
		'tt_products_cat' => 'Categor�a de producto',
	),
	'nl' => Array (
		'tt_products' => 'Producten',
		'tt_products.price' => 'Prijs:',
		'tt_products.price2' => 'Prijs (2):',
		'tt_products.itemnumber' => 'Item nummer:',
		'tt_products.inStock' => 'Per Stuk (stks):',
		'tt_products_cat' => 'Product categorie',
	),
	'cz' => Array (
		'tt_products' => 'Produkty',
		'tt_products.price' => 'Cena:',
		'tt_products.price2' => 'Cena (2):',
		'tt_products.itemnumber' => '��slo polo�ky:',
		'tt_products.inStock' => 'Na sklad� (ks):',
		'tt_products_cat' => 'Kategorie produktu',
	),
	'pl' => Array (
		'tt_products' => 'Produkty',
		'tt_products.price' => 'Cena:',
		'tt_products.price2' => 'Cena2:',
		'tt_products.price2_qty' => 'Cena2 od ilości:',
        'tt_products.price_factor' => 'Mnożnik ceny:',	
		'tt_products.weight' => 'Cięzar [kg]:',			
		'tt_products.unit' => 'Jednostka miary',
		'tt_products.unit_factor' => 'Mnożnik',				
		'tt_products.itemnumber' => 'Kod:',
		'tt_products.inStock' => 'Dostępna ilość:',
		'tt_products.inStock_low' => 'Niski zapas poniżej:',
		'tt_products.on_demand' => 'Na zamówienie (dni):',		
		'tt_products.datasheet' => 'Karta katalogowa (pdf)',		
		'tt_products_language_overlay' => 'Produkty (język alternatywny)',
		'tt_products_language_overlay.prd_uid' => 'Rekord produktu',
		'tt_products_language_overlay.sys_language_uid' => 'Język',
		'tt_products_language_overlay.datasheet' => 'Karta katalogowa (pdf)',		
		'tt_products_cat' => 'Kategoria produktu',
		'tt_products_cat.parent_cat' => 'Kategoria nadrzędna',		
		'tt_products_cat_language_overlay' => 'Kategoria produktu (język alternatywny)',
		'tt_products_cat_language_overlay.sys_language_uid' => 'Język',
		'tt_products_cat_language_overlay.cat_uid' => 'Rekord kategori produktu',
        'tt_products_post_rates' => 'Koszty wysyłki',	
	    'tt_products_post_rates.weight_limit' => 'Waga do [kg]:',
	    'tt_products_post_rates.local_rate' => 'W kraju :',	
	    'tt_products_post_rates.a1_rate' => 'Strefa A1 :',
	    'tt_products_post_rates.a2_rate' => 'Strefa A2 :',
	    'tt_products_post_rates.a3_rate' => 'Strefa A3 :',
	    'tt_products_post_rates.a4_rate' => 'Strefa A4 :',
	    'tt_products_post_rates.a5_rate' => 'Strefa A5 :',
	    'tt_products_post_rates.b_rate' => 'Strefa B:',
	    'tt_products_post_rates.c_rate' => 'Strefa C :',
	    'tt_products_post_rates.d_rate' => 'Strefa D :',	
		"tt_content.list_type_pi1" => "Produkty",		
		'tt_content.pi_flexform.display_mode' => 'Tryb wyświetlania',
		'tt_content.pi_flexform.display_mode.1' => 'Produkty: lista',
	    'tt_content.pi_flexform.display_mode.2' => 'Produkty: wybrane',
		'tt_content.pi_flexform.display_mode.3' => 'Produkty: pojedynczo',
		'tt_content.pi_flexform.display_mode.4' => 'Produkty: wyszukiwanie',	
		'tt_content.pi_flexform.display_mode.5' => 'Koszyk: zawartość',
		'tt_content.pi_flexform.display_mode.6' => 'Koszyk: płatność',
		'tt_content.pi_flexform.display_mode.7' => 'Koszyk: zakończenie',		
		'tt_content.pi_flexform.display_mode.8' => 'Koszyk: informacja',
		'tt_content.pi_flexform.display_mode.9' => 'Zamówienia: śledzenie',	
		'tt_content.pi_flexform.display_mode.10' => 'Waluta: wybór',	
		'tt_content.pi_flexform.display_mode.11' => 'Licznik produktów',
		'tt_products.prd_config' => "Konfiguracja produktu:",
	),
	'si' => Array (
		'tt_products' => 'Izdelki',
		'tt_products.price' => 'Cena:',
		'tt_products.price2' => 'Cena (2):',
		'tt_products.itemnumber' => '�t. izdelka:',
		'tt_products.inStock' => 'Na zalogi (kom):',
	),
	'fi' => Array (
		'tt_products' => 'Tuotteet:',
		'tt_products.price' => 'Hinta:',
		'tt_products.price2' => 'Hinta (2):',
		'tt_products.itemnumber' => 'Tuote numero:',
		'tt_products.inStock' => 'Varastossa (kpl)',
		'tt_products_cat' => 'Tuoteluokka',
	),
	'tr' => Array (
		'tt_products' => '�r�nler',
		'tt_products.price' => 'Fiyat:',
		'tt_products.price2' => 'Fiyat (2):',
		'tt_products.itemnumber' => 'Nesne numaras�:',
		'tt_products.inStock' => 'Stoktaki (pr�):',
		'tt_products_cat' => '�r�n kategorisi',
	),
	'se' => Array (
		'tt_products' => 'Produkter',
		'tt_products.price' => 'Pris:',
		'tt_products.price2' => 'Pris (2):',
		'tt_products.itemnumber' => 'Produkt nr:',
		'tt_products.inStock' => 'I lager (st):',
		'tt_products_cat' => 'Produktkategori',
	),
	'pt' => Array (
		'tt_products' => 'Produtos',
		'tt_products.price' => 'Pre�o:',
		'tt_products.price2' => 'Pre�o (2):',
		'tt_products.itemnumber' => 'N�mero do item:',
		'tt_products.inStock' => 'Em armaz�m (p�s):',
		'tt_products_cat' => 'Categoria do produto',
	),
	'ru' => Array (
		'tt_products' => '��������',
		'tt_products.price' => '����:',
		'tt_products.price2' => '���� (2):',
		'tt_products.itemnumber' => '������������:',
		'tt_products.inStock' => '�� ������ (����):',
		'tt_products_cat' => '��������� ���������',
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
		'tt_products' => 'Produkty',
		'tt_products.price' => 'Cena:',
		'tt_products.price2' => 'Cena (2):',
		'tt_products.itemnumber' => '��slo polo�ky:',
		'tt_products.inStock' => 'V sklade (ks)',
		'tt_products_cat' => 'Kateg�ria v�robku',
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
		'tt_products' => 'Term�kek',
		'tt_products.price' => '�r:',
		'tt_products.price2' => '�r (2):',
		'tt_products.itemnumber' => 'T�telsz�m:',
		'tt_products.inStock' => 'Rakt�ron (pcs):',
		'tt_products_cat' => 'Term�k kateg�ria',
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
		'tt_products' => '���~',
		'tt_products.price' => '���G',
		'tt_products.price2' => '���]���^�G',
		'tt_products.itemnumber' => '�f�~�s���G',
		'tt_products.inStock' => '�w�s�]��^�G',
		'tt_products_cat' => '���~���O',
	),
	'eu' => Array (
	),
	'bg' => Array (
		'tt_products' => '��������',
		'tt_products.price' => '����:',
		'tt_products.price2' => '���� (2):',
		'tt_products.itemnumber' => '����� �� ��������:',
		'tt_products.inStock' => '�� ����� (����):',
		'tt_products_cat' => '���������� ���������',
	),
	'br' => Array (
		'tt_products' => 'Produtos',
		'tt_products.price' => 'Pre�o:',
		'tt_products.price2' => 'Pre�o (2):',
		'tt_products.itemnumber' => 'N�mero do �tem:',
		'tt_products.inStock' => 'Em estoque (un):',
		'tt_products_cat' => 'Categoria do produto',
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
);
?>